apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend1
  name: frontend1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend1
    spec:
      containers:
      - image: httpd
        imagePullPolicy: Always
        name: httpd
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend2
  name: frontend2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend2
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend1
  name: frontend1service
  namespace: default
spec:
  clusterIP: 10.100.57.211
  clusterIPs:
  - 10.100.57.211
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend2
  name: frontend2service
  namespace: default
spec:
  clusterIP: 10.100.10.82
  clusterIPs:
  - 10.100.10.82
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend3
  name: frontend3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend3
    spec:
      containers:
      - image: pavanelthepu/todo-ui:1.0.2
        imagePullPolicy: Always
        name: nginx3
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend3
  name: frontend3service
  namespace: default
spec:
  clusterIP: 10.100.58.213
  clusterIPs:
  - 10.100.58.213
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend3
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
