apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend3
  template:
    metadata:
      labels:
        app: frontend3
    spec:
      containers:
      - image: xcevor/pig-game-web:ingress
        name: pig-game-web
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend3service
spec:
  selector:
    app: frontend3
  ports:
  - port: 80
